//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// oedit.rc で使用
//
#define IDR_MANIFEST                    1
#define IDALLYES                        4
#define IDALLNO                         5
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_OEDITTYPE                   129
#define IDR_DUMMY                       130
#define IDD_PRINT_DLG                   131
#define IDC_LINKCURSOR                  132
#define IDD_SEARCH_DLG                  133
#define IDR_EDIT_MODE                   134
#define IDD_REPLACE_DLG                 135
#define IDD_FILE_FORMAT_DLG             137
#define IDD_OPT_EDITOR                  138
#define IDR_EDIT_MENU                   139
#define IDD_OPT_SETUP                   140
#define IDR_TAB_MENU                    141
#define IDD_LINE_JUMP_DLG               142
#define IDD_QUERY_CLOSE_DLG             143
#define IDD_SELECT_COLOR_DLG            145
#define IDC_SPOIT_CURSOR                146
#define IDR_URL_MENU                    148
#define IDB_CLOSE_BTN                   149
#define IDB_CLOSE_BTN2                  150
#define IDB_CLOSE_BTN3                  151
#define IDD_ACCELERATOR_DLG             155
#define IDD_OPT_EDITOR2                 156
#define IDD_EXT_FILEDLG_OPEN            157
#define IDD_EXT_FILEDLG_SAVE            158
#define IDD_BOOKMARK_DLG                159
#define IDD_LICENSE_MSG_DLG             164
#define IDD_OPT_SETUP2                  165
#define IDB_TOOLBAR1_256                166
#define IDD_FILTER_DLG                  167
#define IDC_CHECK_PRINT_SELECTED_AREA   1015
#define IDC_CHECK_SHOW_LINE_END         1021
#define IDC_CHECK_BOOT_ON_IME           1052
#define IDC_CHECK_SET_SAVE_DLG_FILE_TYPE 1053
#define IDC_EDIT_WHEEL_SCROLL_ROW       1054
#define IDC_CHECK_ENABLE_TAG_JUMP       1057
#define IDC_CHECK_SEARCH_DLG_CLOSE_AT_FOUND 1058
#define IDC_CHECK_SHOW_SPACE            1060
#define IDC_BTN_IME_CARET_COLOR         1067
#define IDC_CHECK_ROW_COPY_AT_NO_SEL    1071
#define IDC_CHECK_KEYWORD_WINDOW        1072
#define IDC_BTN_RULED_LINE_COLOR        1073
#define IDC_CHECK_CLEAR_AFTER_COPY      1073
#define IDC_CHECK_SHOW_BRACKETS_BOLD    1076
#define IDC_CHECK_SHOW_RULED_LINE       1077
#define IDC_COMBO_FILE_OPEN_KANJI_CODE  1083
#define IDC_COMBO_EDIT_MODE             1084
#define IDC_CHECK_ENABLE_WORD_WRAP      1206
#define IDC_CHECK_ENABLE_CONFINEMENT    1207
#define IDC_EDIT_FIRST_CONFINEMENT_STR  1208
#define IDC_EDIT_LAST_CONFINEMENT_STR   1209
#define IDC_COMBO_FORMAT                1210
#define IDC_EDIT_BRACKETS_BLINK_TIME    1213
#define IDC_CHECK_OGREP_DIR_AS_CURRENT_DIR 1214
#define IDC_BUTTON_ADD                  1217
#define IDC_BTN_BOTTOM                  1218
#define IDC_BUTTON_DEL                  1218
#define IDC_BUTTON_UP                   1219
#define IDC_BUTTON_DOWN                 1220
#define IDC_LIST_BOOKMARK               1221
#define IDC_COMBO_SEARCH_TEXT           1900
#define ID_BTN_NEXT                     1901
#define ID_BTN_PREV                     1902
#define IDC_CHECK_DISTINCT_LWR_UPR      1903
#define IDC_CHECK_REGEXP                1904
#define IDC_COMBO_REPLACE_TEXT          1905
#define ID_BTN_REPLACE                  1906
#define ID_BTN_REPLACE_ALL              1907
#define IDC_RADIO_SELECTED_AREA         1908
#define IDC_RADIO_ALL                   1909
#define ID_BTN_FILTER                   1910
#define IDC_COMBO_ACTION                1911
#define IDC_CHECK_DISTINCT_WIDTH_ASCII  1912
#define IDC_STATIC_VERSION              2000
#define IDC_COMBO_PRINTER               2002
#define IDC_EDIT_SPACE_LEFT             2003
#define IDC_EDIT_SPACE_RIGHT            2004
#define IDC_EDIT_SPACE_TOP              2005
#define IDC_EDIT_NEW_KEY                2006
#define IDC_EDIT_LICENSE                2007
#define IDC_EDIT_SPACE_BOTTOM           2008
#define IDC_CHECK_PRINT_TITLE           2009
#define IDC_BTN_ADD                     2010
#define IDC_CHECK_PRINT_PAGE            2011
#define IDC_STATIC_URL                  2012
#define IDC_BTN_DELETE                  2013
#define IDC_CHECK_PRINT_ROW_NUM         2014
#define IDC_EDIT_MAX_MRU                2015
#define IDC_EDIT_TABSTOP                2016
#define IDC_EDIT_INITIAL_DIR            2017
#define IDC_STATIC_PAGE_INFO            2018
#define IDC_CHECK_SHOW_LINE_FEED        2019
#define IDC_EDIT_KEYWORD_FILE           2021
#define IDC_EDIT_LINE_NO                2022
#define IDC_EDIT_BROWSER_03             2023
#define IDC_STATIC_FONT                 2024
#define IDC_COMBO_KANJI_CODE            2025
#define IDC_CHECK_PRINT_DATE            2026
#define IDC_CHECK_SHOW_TAB              2027
#define IDC_STATIC_MSG                  2029
#define IDC_COMBO_INDENT                2030
#define IDC_EDIT_BROWSER_01             2031
#define IDC_STATIC_FONT_SIZE            2032
#define IDC_EDIT_BROWSER_02             2032
#define IDC_COMBO_LINE_TYPE             2033
#define IDC_BTN_TEXT_COLOR              2034
#define IDC_STATIC_ICON                 2035
#define IDC_PRINTER_SETUP               2036
#define IDC_BTN_KEYWORD_COLOR           2038
#define IDC_SET_FONT                    2039
#define IDC_BTN_COMMENT_COLOR           2040
#define IDC_BTN_BG_COLOR                2041
#define IDC_BTN_PEN_COLOR               2042
#define IDC_BTN_QUOTE_COLOR             2043
#define IDC_BTN_DEFAULT_COLOR           2044
#define IDC_CHECK_SHOW_ROW_NUM          2045
#define IDC_BTN_INITIAL_DIR             2046
#define IDC_CHECK_SHOW_COL_NUM          2047
#define IDC_BTN_KEYWORD_FILE            2048
#define IDC_BTN_BROWSER_03              2049
#define IDC_CHECK_REGISTER_SHELL        2050
#define IDC_EDIT_ROW_SPACE              2051
#define IDC_BTN_BROWSER_01              2052
#define IDC_CHECK_SAVE_MODIFIED         2053
#define IDC_BTN_BROWSER_02              2053
#define IDC_EDIT_CHAR_SPACE             2054
#define IDC_EDIT_TOP_SPACE              2055
#define IDC_CHECK_WINDOW_TITLE_IS_PATH_NAME 2056
#define IDC_EDIT_LEFT_SPACE             2057
#define IDC_CHECK_SEARCH_LOOP_MSG       2058
#define IDC_EDIT_LINE_LEN               2059
#define IDC_COMBO_FILE_LIST_FILTER      2060
#define IDC_CHECK_SHOW_2BYTE_SPACE      2062
#define IDC_CHECK_TAB_TITLE_IS_PATH_NAME 2063
#define IDC_CHECK_DISABLE_DOUBLE_BOOT   2064
#define IDC_BTN_SEARCH_COLOR            2065
#define IDC_CHECK_TAB_MULTI_ROW         2065
#define IDC_BTN_SELECTED_COLOR          2066
#define IDC_CHECK_TAB_CLOSE_AT_MCLICK   2066
#define IDC_CHECK_AUTO_INDENT           2067
#define IDC_CHECK_HIDE_TAB_BAR_AT_ONE   2067
#define IDC_BTN_KEYWORD2_COLOR          2068
#define IDC_BTN_BK_COLOR2               2068
#define IDC_BTN_RULER_COLOR             2069
#define IDC_CHECK_TAB_DRAG_MOVE         2069
#define IDC_CHECK_CLICKABLE_URL         2070
#define IDC_CHECK_CLOSE_BTN_ON_TAB      2070
#define IDC_CHECK_TAB_AS_SPACE          2071
#define IDC_CHECK_SHOW_TAB_TOOLTIP      2071
#define IDC_CHECK_DRAG_DROP_EDIT        2072
#define IDC_CHECK_TAB_CREATE_AT_DBLCLICK 2072
#define IDC_CHECK_SHOW_ROW_LINE         2073
#define IDC_CHECK_TEXT_DROP_EDIT        2073
#define IDC_CHECK_MOUSE_SELECT_COPY     2074
#define IDC_BTN_OPERATOR_COLOR          2076
#define IDC_SEL_COLOR_BTN               2077
#define IDC_CHECK_SHOW_EDIT_ROW         2079
#define IDC_EDIT_RGB                    2080
#define IDC_STATIC_RESULT               2081
#define IDC_LIST_CATEGORY               2082
#define IDC_LIST_COMMAND                2083
#define IDC_LIST_ACCEL                  2084
#define IDC_BTN_DEFAULT                 2085
#define IDC_STATIC_CURRENT_MENU         2086
#define IDC_BTN_LICENSE                 2087
#define IDC_STATIC_LICENSE              2088
#define IDC_BTN_BK_COLOR                2092
#define IDC_STATIC_KANJI_CODE           2093
#define IDC_STATIC_LINE_TYPE            2094
#define IDOK2                           2124
#define ID_SELECT_ALL                   32771
#define ID_OPTION                       32772
#define ID_FONT                         32773
#define ID_SET_FONT                     32774
#define ID_SEARCH                       32783
#define ID_REPLACE                      32790
#define ID_SEARCH_NEXT                  32794
#define ID_SEARCH_PREV                  32795
#define ID_EDIT_INDENT                  32846
#define ID_EDIT_INDENT_REV              32847
#define ID_DELETE_SPACE                 32848
#define ID_DELETE_SPACE_END             32849
#define ID_INSERT_GT                    32850
#define ID_DELETE_GT                    32851
#define ID_INSERT_COMMENT               32860
#define ID_DELETE_COMMENT               32861
#define ID_TO_LOWER                     32900
#define ID_TO_UPPER                     32901
#define ID_EDIT_REVERSE_ROWS            32902
#define ID_EDIT_SORT_ROWS_ASC           32903
#define ID_EDIT_SORT_ROWS_DESC          32904
#define ID_ACCELERATOR                  32905
#define ID_CHAR_LEFT                    32906
#define ID_CHAR_RIGHT                   32907
#define ID_CHAR_UP                      32908
#define ID_LINE_UP                      32909
#define ID_LINE_DOWN                    32910
#define ID_WORD_LEFT                    32911
#define ID_LINE_START                   32912
#define ID_LINE_END                     32913
#define ID_DOCUMENT_START               32914
#define ID_LINE_MODE_NORMAL             32915
#define ID_LINE_MODE_RIGHT              32916
#define ID_LINE_MODE_LEN                32917
#define ID_DOCUMENT_END                 32918
#define ID_LINE_MODE_NORMAL2            32919
#define ID_CHAR_LEFT_EXTEND             32920
#define ID_DOCUMENT_END2                32921
#define ID_CHAR_RIGHT_EXTEND            32922
#define ID_LINE_MODE_RIGHT2             32923
#define ID_LINE_UP_EXTEND               32924
#define ID_LINE_MODE_LEN2               32925
#define ID_LINE_DOWN_EXTEND             32926
#define ID_CHAR_LEFT_EXTEND2            32927
#define ID_WORD_LEFT_EXTEND             32928
#define ID_CHAR_RIGHT_EXTEND2           32929
#define ID_EDIT_DELETE                  32930
#define ID_WORD_RIGHT                   32931
#define ID_WORD_RIGHT_EXTEND            32934
#define ID_LINE_START_EXTEND            32936
#define ID_LINE_END_EXTEND              32937
#define ID_LINE_UP_EXTEND2              32938
#define ID_DOCUMENT_START_EXTEND        32939
#define ID_LINE_DOWN_EXTEND2            32940
#define ID_DOCUMENT_END_EXTEND          32941
#define ID_WORD_LEFT_EXTEND2            32942
#define ID_PAGE_UP                      32944
#define ID_PAGE_DOWN                    32946
#define ID_PAGE_UP_EXTEND               32947
#define ID_WORD_RIGHT2                  32948
#define ID_NEW_WINDOW                   32949
#define ID_PAGE_DOWN_EXTEND             32950
#define ID_EDIT_BACKSPACE               32952
#define ID_WORD_RIGHT_EXTEND2           32953
#define ID_KEYWORD_COMPLETION           32954
#define ID_LINE_START_EXTEND2           32955
#define ID_KEYWORD_COMPLETION_REV       32956
#define ID_LINE_END_EXTEND2             32957
#define ID_VIEW_TOOLBAR_EDIT_MODE       32958
#define ID_COLOR_INPUT                  32959
#define ID_SCROLL_DOWN                  32960
#define ID_SCROLL_UP                    32961
#define ID_DOCUMENT_START_EXTEND2       32962
#define ID_SCROLL_PAGE_UP               32963
#define ID_DOCUMENT_END_EXTEND2         32964
#define ID_VIEW_BROWSER_03              32965
#define ID_SCROLL_PAGE_DOWN             32966
#define ID_SELECT_ROW                   32967
#define ID_PAGE_UP2                     32968
#define ID_PAGE_DOWN2                   32969
#define ID_CLEAR_SEARCH_TEXT            32970
#define ID_PAGE_UP_EXTEND2              32971
#define ID_FILE_LOAD_EUC                32972
#define ID_FILE_LOAD_SJIS               32973
#define ID_FILE_LOAD_JIS                32974
#define ID_PAGE_DOWN_EXTEND2            32991
#define ID_EDIT_BACKSPACE2              32992
#define ID_KEYWORD_COMPLETION2          32993
#define ID_KEYWORD_COMPLETION_REV2      32994
#define ID_SET_FILE_FORMAT              32995
#define ID_SEARCH_FILE                  32996
#define ID_SCROLL_DOWN2                 32997
#define ID_SCROLL_UP2                   32998
#define ID_SCROLL_PAGE_UP2              32999
#define ID_LINE_JUMP                    33000
#define ID_EXT_REG                      33001
#define ID_SCROLL_PAGE_DOWN2            33002
#define ID_SELECT_ROW2                  33003
#define ID_BOX_SELECT                   33004
#define ID_SET_BOOK_MARK                33010
#define ID_JUMP_BOOK_MARK               33011
#define ID_JUMP_BOOK_MARK_BACK          33012
#define ID_CLEAR_ALL_BOOK_MARK          33013
#define ID_TOGGLE_OVERWRITE             33020
#define ID_SHOW_TOPMOST                 33022
#define ID_NEXT_WINDOW                  33025
#define ID_PREV_WINDOW                  33026
#define ID_TAB_MOVE_LEFT                33027
#define ID_TAB_MOVE_RIGHT               33028
#define ID_TAB_MOVE_TOP                 33029
#define ID_TAB_MOVE_LAST                33030
#define ID_TAB_TO_SPACE                 33031
#define ID_SPACE_TO_TAB                 33032
#define ID_FILE_CLOSE_ALL               33200
#define ID_VIEW_FILE_BAR                33201
#define ID_SORT_TAB                     33202
#define ID_JUMP_BOOK_MARK_EXTEND        33400
#define ID_JUMP_BOOK_MARK_BACK_EXTEND   33401
#define ID_PLAY_KBMACRO                 33404
#define ID_REC_KBMACRO                  33405
#define ID_VIEW_BROWSER_01              33411
#define ID_EDIT_DELETE_ROW              33414
#define ID_EDIT_DELETE_AFTER_CURSOR     33415
#define ID_LAST_EDIT_POS                33416
#define ID_EDIT_CUT_ROW                 33417
#define ID_EDIT_COPY_ROW                33418
#define ID_EDIT_PASTE_ROW               33419
#define ID_EDIT_PASTE_ROW_UP            33421
#define ID_SPLIT_START                  33451
#define ID_SPLIT_END                    33452
#define ID_SPLIT_START_EXTEND           33453
#define ID_SPLIT_END_EXTEND             33455
#define ID_FILE_LOAD_UNICODE            33456
#define ID_FILE_LOAD_UTF8               33457
#define ID_FILE_LOAD_AUTO               33458
#define ID_FILE_RELOAD                  33459
#define ID_KBMACRO_SAVE                 33460
#define ID_KBMACRO_LOAD                 33461
#define ID_KBMACRO_PLAY                 33462
#define ID_SELECT_WORD                  33475
#define ID_COPY_CLICKABLE_URL           33480
#define ID_DO_CLICKABLE_URL             33481
#define ID_VIEW_CLICKABLE_URL_01        33482
#define ID_VIEW_CLICKABLE_URL_02        33483
#define ID_VIEW_CLICKABLE_URL_03        33484
#define ID_VIEW_CLICKABLE_URL_01_NEW_WINDOW 33485
#define ID_VIEW_CLICKABLE_URL_03_NEW_WINDOW 33487
#define ID_EDIT_JOIN_ROW                33492
#define ID_REDRAW                       33493
#define ID_SEARCH_SELECTED              33494
#define ID_HANKAKU_TO_ZENKAKU           33499
#define ID_ZENKAKU_TO_HANKAKU           33500
#define ID_HANKAKU_TO_ZENKAKU_KATA      33501
#define ID_HANKAKU_TO_ZENKAKU_ALPHA     33502
#define ID_ZENKAKU_TO_HANKAKU_KATA      33503
#define ID_ZENKAKU_TO_HANKAKU_ALPHA     33504
#define ID_SPLIT_ROWS                   33520
#define ID_JOIN_ROWS                    33521
#define ID_INPUT_RETURN                 33602
#define ID_FILE_INSERT                  33603
#define ID_EDIT_DELETE_BEFORE_CURSOR    33604
#define ID_INPUT_BR                     33605
#define ID_EDIT_DELETE_WORD_AFTER_CURSOR 33606
#define ID_EDIT_DELETE_WORD_BEFORE_CURSOR 33607
#define ID_INVERT_BRACKETS              33608
#define ID_GO_MATCH_BRACKETS            33609
#define ID_EDIT_INDENT_SPACE            33610
#define ID_EDIT_INDENT_SPACE_REV        33611
#define ID_SPACE_LEFT                   33614
#define ID_SPACE_RIGHT                  33615
#define ID_SPACE_LEFT_EXTEND            33616
#define ID_SPACE_RIGHT_EXTEND           33617
#define ID_TOGGLE_SHOW_ROW_NUM          33618
#define ID_TOGGLE_SHOW_COL_NUM          33619
#define ID_EDIT_DEL_DUP_ROWS            33620
#define ID_SHOW_REGEXP_HELP             33621
#define ID_SCM_EVAL                     33623
#define ID_SCM_LOAD_FILE                33624
#define ID_SHOW_SCHEME_HELP             33625
#define ID_SHOW_OEDITMACRO_HELP         33626
#define ID_SCM_EVAL_CLIPBOARD           33627
#define ID_SEARCH_SELECTED_PREV         33628
#define ID_CHAR_LEFT_EXTEND_BOX         33629
#define ID_CHAR_RIGHT_EXTEND_BOX        33631
#define ID_LINE_UP_EXTEND_BOX           33632
#define ID_LINE_DOWN_EXTEND_BOX         33633
#define ID_FONT_SIZE_LARGE              33634
#define ID_FONT_SIZE_SMALL              33635
#define ID_BOX_PASTE                    33636
#define ID_VIEW_BROWSER_02              33641
#define ID_FILE_LOAD_UTF16BE            33646
#define ID_FILE_LOAD_UTF16BE_NO_SIGNATURE 33647
#define ID_WORD_LEFT_STOP_WB            33648
#define ID_WORD_RIGHT_STOP_WB           33649
#define ID_WORD_LEFT_STOP_WB_EXTEND     33652
#define ID_WORD_RIGHT_STOP_WB_EXTEND    33653
#define ID_TAG_JUMP                     34000
#define ID_INSERT_DATE_TIME             34001
#define ID_FILTER                       34002
#define ID_EDIT_MODE_1                  34101
#define ID_EDIT_MODE_2                  34102
#define ID_EDIT_MODE_3                  34103
#define ID_EDIT_MODE_4                  34104
#define ID_EDIT_MODE_5                  34105
#define ID_EDIT_MODE_6                  34106
#define ID_EDIT_MODE_7                  34107
#define ID_EDIT_MODE_8                  34108
#define ID_EDIT_MODE_9                  34109
#define ID_EDIT_MODE_10                 34110
#define ID_EDIT_MODE_11                 34111
#define ID_EDIT_MODE_12                 34112
#define ID_EDIT_MODE_13                 34113
#define ID_EDIT_MODE_14                 34114
#define ID_EDIT_MODE_15                 34115
#define ID_FILE_SAVE_ALL                34200
#define ID_FILE_LOAD_UNICODE_NO_SIGNATURE 34202
#define ID_FILE_LOAD_UTF8_NO_SIGNATURE  34203
#define ID_SET_FONT_TAB_CTRL            34204
#define ID_FILE_BOOKMARK                34207
#define ID_34208                        34208
#define ID_SHOW_CREDITS                 34209
#define ID_TAB_CLOSE_RIGHT              35281
#define ID_TAB_CLOSE_LEFT               35282
#define ID_TAB_CLOSE_OTHER              35283
#define ID_INDICATOR_CURSOR_POS         59143
#define ID_INDICATOR_FILE_TYPE          59144
#define ID_INDICATOR_BOX_SELECT         59145

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        161
#define _APS_NEXT_COMMAND_VALUE         34210
#define _APS_NEXT_CONTROL_VALUE         2095
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
